return {
  "goolord/alpha-nvim",
  event = "VimEnter",
  config = function()
    local alpha = require("alpha")
    local dashboard = require("alpha.themes.dashboard")

    local moorby_logo = {
      "    __  ___      ____       ____       ",
      "   /  |/  /___  / __ \\_____/ __ )__  __",
      "  / /|_/ / __ \\/ / / / ___/ __  / / / /",
      " / /  / / /_/ / /_/ / /  / /_/ / /_/ / ",
      "/_/  /_/\\____/\\____/_/  /_____/\\__, /  ",
      "                              /____/   "
    }
    -- Generated by https://patorjk.com/software/taag/#p=display&f=Slant&t=Mo0rBy%0A
    -- (some extra characters are needed due to "escape characters" being used)

    -- Set header
    dashboard.section.header.val = moorby_logo

    -- Set menu buttons
    dashboard.section.buttons.val = {
      dashboard.button("e", "  > New file" , ":ene <BAR> startinsert <CR>"),
      dashboard.button("SPC ff", "󰈞  > Find file", ":Telescope find_files<CR>"),
      dashboard.button("SPC fg", "  > Find word", ":Telescope live_grep<CR>"),
      dashboard.button("SPC fr", "  > Recent"   , ":Telescope oldfiles<CR>"),
      dashboard.button("SPC wr", "󰁯  > Restore Session For Current Directory", ":SessionRestore<CR>"),
      dashboard.button("c", "  > Configuration" , ":e $XDG_CONFIG_HOME/nvim<CR>"),
      dashboard.button("q", "  > Quit NVIM", ":qa<CR>"),
    }

    alpha.setup(dashboard.opts)

    vim.cmd([[autocmd FileType alpha setlocal nofoldenable]])
  end
}
